Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"
  
  # Application 1 VM
  config.vm.define "app1" do |app1|
    app1.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/application1_playbook.yml"
    end
  end
  # Application 2 VM
  config.vm.define "app2" do |app2|
    app2.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/application2_playbook.yml"
    end
  end
end




























































